### PR TITLE
Fix immediate theme change issue in dark mode script

### PR DESCRIPTION
**Pull request by Shubham18024**
Hello,

I noticed that the original dark mode script does not immediately change the theme when pasted into the console. The current implementation only sets up keyboard shortcuts, which means the user has to manually trigger the theme change.

Changes Made:
Added an immediate invocation of the change_theme() function at the end of the script.

### CODE REVIEW

**Comment by FireHead90544** [comment]
Hi Shubham, 
Thanks for mentioning it out. I don't even know if this darkmode works now, but sure I'll merge this in a while.

**Comment by Shubham18024** [comment]
Oh thank you so much.

**Comment by FireHead90544** [comment]
tested and merged.

**Comment by Shubham18024** [comment]
👍👍

**Pull request merged**
